### ISSUE TITLE
Convolve header

### ISSUE THREAD

**Issue by iPowerWheels** [fps/jack_convolve#1]
Hello, I'm trying to compiling it as instructions provided with your readme... so, I encoured with a little issue, there's no header file for convolve... and, I looked everywhere so, there's no answers tho

**Comment by fps** [comment]
Hi,

this is a suuuuper old project, so I'm actually not completely sure which header to use there. Probably the one from: https://github.com/fps/libconvolve 

But I would probably recommend looking at Fons Adriaensen's jconvolver https://kokkinizita.linuxaudio.org/linuxaudio/downloads/index.html

That one is the clearly superior software!
